version: "3"
services:
  go-todo-backend:
    build: .
    environment:
      DB_DSN: postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - 8080:8080

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.0
    ports:
      - 9090:8080

  swagger:
    image: swaggerapi/swagger-ui:v3.45.1
    environment:
      SWAGGER_JSON: /etc/go-todo-backend/swagger.json
    ports:
      - 9091:8080
    volumes:
      - ./docs:/etc/go-todo-backend
