version: "3"
services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.0
    ports:
      - 9090:8080
